server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/employees
    username: employees
    password: employees
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:db/db-changelog.yaml
  cloud:
    function:
      definition: createEmployee;tick
    stream:
#      function:
#        bindings:
#          createEmployee-in-0: employee-backend-command
#          createEmployee-out-0: employee-backend-event
      bindings:
        createEmployee-in-0:
#          error-handler-definition: employeesErrorHandler
          destination: employee-backend-command
          group: employee-backend
        createEmployee-out-0:
          destination: employee-backend-event
        tick-out-0:
          producer:
            poller:
              initial-delay: 0
              fixed-delay: 5000
          destination: employee-backend-tick
      kafka:
        bindings:
          createEmployee-in-0:
            consumer:
              enable-dlq: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE
