POST http://localhost:8080/calculate
Content-Type: application/json

{
  "a": 1.1234,
  "b": 2.1234
}

###
POST http://localhost:8080/calculate,round
Content-Type: application/json

{
  "a": 1.1234,
  "b": 2.1234
}

