server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    employees: DEBUG
    org.hibernate.SQL: TRACE

employees:
  backend-url: http://localhost:8081

spring:
  application:
    name: employees-frontend
  cloud:
    stream:
      function:
        bindings:
          employeeCreated-in-0: employee-backend-event
      kafka:
        binder:
          enable-observation: true
